version: "3.8"

services:
  onp-app:
    build: .
    container_name: onp-app
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  init-db:
    build: .
    container_name: init-db
    command: python -c "import os; print('>>> contenu du répertoire:', os.listdir('.')); import init_db"
    volumes:
      - .:/app
    depends_on:
      - onp-app
