version: "3.8"

services:
  onp-app:
    build: .
    container_name: onp-app
    ports:
      - "80:5000"
    restart: always
  init-db:
    build: .
    command: python init_db.py
    volumes:
      - .:/app
