services:
  onp-app:
    build: .
    container_name: onp-app
    command: gunicorn -w 4 -b 0.0.0.0:5000 main:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mailhog
    environment:
      - DOCKER_ENV=1   # 👉 pour indiquer à Flask qu’on est dans Docker

  init-db:
    build: .
    container_name: init-db
    command: python -c "import init_db"
    volumes:
      - .:/app
    depends_on:
      - onp-app

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # interface web
      - "1025:1025"  # serveur SMTP
